// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryWithCompositeKeys;

namespace RepositoryWithCompositeKeys.Migrations
{
    [DbContext(typeof(CompositeKeyContext))]
    [Migration("20210115131040_repro")]
    partial class repro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compkey")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("RepositoryWithCompositeKeys.Order", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MostImportantOrderLine")
                        .HasColumnType("int");

                    b.HasKey("CompanyId", "CustomerId", "OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CustomerId = 2,
                            OrderId = 1,
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            MostImportantOrderLine = 2
                        });
                });

            modelBuilder.Entity("RepositoryWithCompositeKeys.OrderLine", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderLineId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderLineNumber")
                        .HasColumnType("int");

                    b.HasKey("CompanyId", "CustomerId", "OrderId", "OrderLineId");

                    b.ToTable("OrderLine");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CustomerId = 2,
                            OrderId = 1,
                            OrderLineId = 1,
                            Description = "ChessSet",
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            OrderLineNumber = 2
                        },
                        new
                        {
                            CompanyId = 1,
                            CustomerId = 2,
                            OrderId = 1,
                            OrderLineId = 2,
                            Description = "NotAChessSet",
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            OrderLineNumber = 3
                        });
                });

            modelBuilder.Entity("RepositoryWithCompositeKeys.OrderLine", b =>
                {
                    b.HasOne("RepositoryWithCompositeKeys.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("CompanyId", "CustomerId", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RepositoryWithCompositeKeys.Order", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
