// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryWithNoCompositeKeys;

namespace RepositoryWithNoCompositeKeys.Migrations
{
    [DbContext(typeof(NoCompositeKeyContext))]
    [Migration("20210115093853_repro")]
    partial class repro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nocompkey")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerGroupId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000010"),
                            CustomerGroupId = new Guid("00000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerGroupSubGroupAlternateKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerGroupSubGroupAlternateKey");

                    b.ToTable("CustomerGroup");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CustomerGroupSubGroupAlternateKey = 1000
                        });
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroupChild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerGroupChildNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerGroupId");

                    b.ToTable("CustomerGroupChild");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CustomerGroupChildNumber = 1,
                            CustomerGroupId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Something"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CustomerGroupChildNumber = 2,
                            CustomerGroupId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "SomethingElse"
                        });
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroupSubGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerGroupAlternateKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CustomerGroupSubGroup");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CustomerGroupAlternateKey = 1000
                        });
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroupSubGroupChild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerGroupSubGroupChildNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerGroupSubGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerGroupSubGroupId");

                    b.ToTable("CustomerGroupSubGroupChild");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CustomerGroupSubGroupChildNumber = 1,
                            CustomerGroupSubGroupId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "Something"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CustomerGroupSubGroupChildNumber = 2,
                            CustomerGroupSubGroupId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "SomethingElse"
                        });
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IntOnOtherSideOfDB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            IntOnOtherSideOfDB = 2
                        });
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.Customer", b =>
                {
                    b.HasOne("RepositoryWithNoCompositeKeys.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryWithNoCompositeKeys.CustomerGroup", "Group")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroup", b =>
                {
                    b.HasOne("RepositoryWithNoCompositeKeys.CustomerGroupSubGroup", "SubGroup")
                        .WithMany("CustomerGroups")
                        .HasForeignKey("CustomerGroupSubGroupAlternateKey")
                        .HasPrincipalKey("CustomerGroupAlternateKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroupChild", b =>
                {
                    b.HasOne("RepositoryWithNoCompositeKeys.CustomerGroup", null)
                        .WithMany("Children")
                        .HasForeignKey("CustomerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroupSubGroupChild", b =>
                {
                    b.HasOne("RepositoryWithNoCompositeKeys.CustomerGroupSubGroup", null)
                        .WithMany("Children")
                        .HasForeignKey("CustomerGroupSubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.Order", b =>
                {
                    b.HasOne("RepositoryWithNoCompositeKeys.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.Company", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("RepositoryWithNoCompositeKeys.CustomerGroupSubGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("CustomerGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
